apiVersion: v1
kind: Service
metadata:
  name: christmas-countdown-service
spec:
  type: LoadBalancer
  selector:
    app: christmas-countdown
  ports:
  - protocol: TCP
    port: 80          # This is the external port (accessible from the browser)
    targetPort: 8080  # This is the container port where the app is running
